# -*- coding: utf-8 -*-
"""Python Programming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LnjLBmuHIUD1tz56BU2i8r5xNS9ZbfHS
"""

print("Welcome to the Quiz Game")

name = input("Enter your name")

  print("\nHello", name)
  print("Answer the following questions:\n")

score = 0

#Question 1

answer1 = input("1. What is the capital of France? ")

if answer1.lower() == "paris":
  print("correct!")
  score += 1
else:
  print("Wrong! The answer is Paris.")

#Question 2

answer2 = input("2. What planet is known as the Red Planet? ")

if answer2.lower() == "mars":
  print("correct!")
  score += 1
else:
  print("Wrong! The answer is Mars.")

#Question 3

answer3 = input("3. What is the largest Ocean in the World? ") # Changed variable name to answer3

if answer3.lower() == "pacific": # Used answer3
  print("correct!")
  score += 1
else:
  print("Wrong! The answer is Pacific.")

  print("\nQuiz Finished!")
  print(name + ", your score is: " + str(score) + "/3") # Corrected print statement concatenation

if score == 3:
  print("Excellent! You got all answers correct. ")
elif score == 2:
  print("Good job! you did well.")
elif score == 1:
  print("You got one correct. Keep practicing.")
else:
  print("Better luck next time!")

"""# New Section"""